### ISSUE TITLE
Missing web app portion of the project

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [NotSoFearfulSymmetry/dAndDCharacterStorage#1]
@NotSoFearfulSymmetry Just so it does not fall off the radar for week 2 deliverables - the basic maven project structure isn't visible here yet.

**Comment by NotSoFearfulSymmetry** [comment]
Is it all right if I close this issue?  @pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
yep!
