### ISSUE TITLE
Checkpoint 1 - Reminder

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [NotSoFearfulSymmetry/dAndDCharacterStorage#3]
- [ ] A reminder to complete checkpoint one, please add detailed screens to capture all aspects of your application - this is used to help your instructor and peer reviewers understand the scope and flow of the application, and to identify all fields needed in the application.
- [ ] Consider breaking down your user stories into smaller pieces of functionality. Refer to the Fat Bike Trail Reports demo repo, or your peer's repositories, for some good user story examples.

**Comment by NotSoFearfulSymmetry** [comment]
I've updated the design documents.

**Comment by NotSoFearfulSymmetry** [comment]
@pawaitemadisoncollege I've updated the wireframes and user stories.  In thinking further about them, and about the database design, I also reconceptualized the application's user permissions, and updated the problem statement accordingly.

**Comment by pawaitemadisoncollege** [comment]
Nice job with your clarifications and updates. 

Have you thought about what api or web service you will utilize?
