### ISSUE TITLE
Peer Review Week 1 Feedback

### ISSUE THREAD

**Issue by yocarrotyo** [NotSoFearfulSymmetry/dAndDCharacterStorage#4]
# Design/Code Review 1

### Reviewer: Caroline Hughes

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person|Good idea to clarify that you don't really use this character sheet *while* you're playing. One of my friends is one of those DnD players who doesn't study his lore, or whatever, and always has to look up information in his binder. Could your site help with that? Could it be a place for a dungeonmaster to push info to the members of the campaign? Maybe as a version 2.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |I like the etremely simple nature of the design. I think image upload would be great.<br>I'm thinking about what cute thing about this repository would make someone feel good about using it. Can they take notes on various different stuff that happens during a round of play?|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>|Looks like characters are children of users. You might want to think about what exactly the admin role should be able to do. (Unlock an account?)<br>Do you have any reason to make a publicly-visible gallery of users' players? What if someone wanted to show off their character and history. Not sure this is how the game works, but it could also help more people understand what the site is about and decide to use it.|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.|Should the data type in Java for feats, equipment, skills, etc be a collection of some sort instead of a single string? (Discussion: this information could be in a hash map, but it might not be necessary since there is minimal processing of this data.) This could help with formatting display of information.<br>JSPs look good. Think about the table dimensions for mobile view.<br><br>I searched through your code and did not find any system.out.println statements, and found that you are using logger.debug in the character and UserDao.<br> <br>Remember to add your database.properties and hibernate.cfg.xml files to the .gitignore and clear them out of the cache.|

**Comment by pawaitemadisoncollege** [comment]
@yocarrotyo nice job with your review comments here. One additional thing regarding the Code feedback. Fid you find any printStackTrace statements or printlns? If so, please indicate where so @NotSoFearfulSymmetry can easily fix them. If not, indicate none were found. Hint: the search feature is in Github can be useful for finding these.

**Comment by yocarrotyo** [comment]
Updated the issue! Looks like you want to do .gitignore cleanup, @NotSoFearfulSymmetry
