### ISSUE TITLE
Code Review 2

### ISSUE THREAD

**Issue by jvjohnson1** [NotSoFearfulSymmetry/dAndDCharacterStorage#5]
# Design/Code Review 2

### Reviewer: Julie Johnson

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Overall this is good.  You explain what you intend to do and why.  The term “gamemaster” is undefined, however.  This is not the place for detailed description of how the game works, but maybe “leader” or “referee” would be a good one-word definition. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Kudos! The design is simple and easy to follow.  Given the nature of the app, there is really no need for anything more here.
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| The amount of information needed to describe a character makes the class large, but you really can’t simplify if the MVP version is to be useful to real players. Opinion – don’t skimp on character detail, but limit to two tables, players and characters.  A simple one-to-many is all that is required.||
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.  | No issues found.

**Comment by pawaitemadisoncollege** [comment]
@jvjohnson1 Missing comments related to the code (you can review this right in GitHub if you like). Example: did you find any printStackTrace statements or printlns? If so, please indicate where so @NotSoFearfulSymmetry can easily fix them. If not, indicate none were found. Thanks!
